spring:
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
  application:
    name: ADDRESS
  config:
    import: configserver:http://localhost:8086
  webflux:
    base-path: /address
server:
  port: 8011
  servlet:
    context-path: /address
    context-path-state: /state/
    context-path-country: /country/
    context-path-district: /district/

management:
  zipkin:
    tracing:
      endpoint: http://localhost:8080/api/v2/spans
  tracing:
    sampling:
      probability: 1.0